@pm_life_cycle_policy.sql
@pm_life_cycle_permission.sql
@pm_cm_message_receiver.sql
@pm_cm_param_switch.sql
@pm_fd_task_config.sql
@pm_fdsearch_main_set.sql
@pm_fdsearch_result_set.sql
@pm_portalpart_info.sql
@pm_partinforole_link.sql
@pm_pm_menu.sql
@pm_pm_template_menu.sql
@pm_rep_file.sql
@pm_sn_generator_rule.sql
@pm_sn_generator_info.sql
@pm_sn_generator_rule_relate.sql
@pm_t_s_function.sql
@pm_t_s_function_relate.sql
@pm_t_s_operation.sql
@pm_t_s_role.sql
@pm_t_s_type.sql
@pm_timer_fd_job.sql
@pm_timer_fd_trigger.sql
@pm_timer_fd_scheduler.sql
@pm_ws_msg_config.sql
@pm_fdplugin_business_link.sql
@pm_object_business_bpmn_link.sql
@pm_planview_info.sql
@pm_planview_column_info.sql
@pm_fd_appinfo.sql
@pm_combination_template_info.sql
@pm_data_source_Object.sql
@pm_object_property_info.sql
@pm_plan_general.sql
@pm_tab_combination_template.sql
@pm_tab_template.sql
@pm_feedback.sql
exit