--基本信息pm_data_source_Object
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('4028f0066d48f35e016d48f8d5ab0011', null, 'com.glaway.ids.project.plan.entity.Plan', 'ids-pm-service', '', '4028f0066d48f35e016d48f864450001', '', '1', 'planNumber,formId,planOrder,isCreateByPmo,planName,projectId,project,projectName,currentUser,parentPlanId,parentPlan,parentPlanName,parentPlanNo,owner,ownerInfo,ownerDept,ownerRealName,implementation,assigner,assignerInfo,assignTime,assignTimeStart,assignTimeEnd,launcher,launcherInfo,launchTime,creator,planLevel,planLevelInfo,planLevelName,progressRate,planStartTime,planStartTimeStart,planStartTimeEnd,planEndTime,planEndTimeStart,planEndTimeEnd,workTime,workTimeReference,actualStartTime,actualStartTimeStart,actualStartTimeEnd,actualEndTime,actualEndTimeStart,actualEndTimeEnd,remark,status,projectStatus,flowStatus,milestone,isAssignBack,isAssignSingleBack,isChangeSingleBack,milestoneName,preposeIds,preposeNos,preposePlans,documents,parentStorey,storeyNo,beforePlanId,feedbackProcInstId,feedbackRateBefore,planSource,fromTemplate,flowResolveXml,opContent,planType,taskType,taskNameType,cellId,required,order,result,flowFlag,_parentId,rescLinkInfoList,deliInfoList,inputList,preposeList,invalidTime,deliverablesName,planTemplateId,isNecessary,planViewInfoId,planReceivedProcInstId,serialVersionUID,bizId,bizVersion,policy,bizCurrent,avaliable,firstBy,firstName,firstFullName,firstOrgId,firstTime,branchIterationId,lastIterationId,latestIteration,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('4028f0066d48f35e016d48fec1fc0012', null, 'com.glaway.ids.project.menu.entity.Project', 'ids-pm-service', '', '4028f0066d48f35e016d48f864450001', '', '1', 'name,projectNumber,status,startProjectTime,endProjectTime,projectTimeType,projectTemplate,remark,queryBefStartProjTime,queryAftStartProjTime,queryBefEndProjTime,queryAftEndProjTime,prevLifeStatus,epsInfo,eps,epsName,phase,phaseInfo,process,isRefuse,projectManagers,projectManagerNames,flowFlag,creator,procInstId,closeTime,pauseTime,serialVersionUID,bizId,bizVersion,policy,bizCurrent,avaliable,firstBy,firstName,firstFullName,firstOrgId,firstTime,branchIterationId,lastIterationId,latestIteration,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

--输入pm_data_source_Object
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('297e02af6d18ed7d016d18f1fd220113', null, 'com.glaway.ids.project.plan.entity.Inputs', 'ids-pm-service', '', '297e02af6d18ed7d016d18f191460112', '', '1', 'name,useObjectType,useObjectId,fileId,origin,required,docId,docName,originObjectId,originObjectName,originObjectNameShow,originDeliverablesInfoId,fileType,versionCode,originDeliverablesInfoName,checked,document,formId,originType,originTypeExt,tempId,havePower,download,detail,securityLeve,docNameShow,originPath,docIdShow,matchFlag,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('297e02af6dce09e3016dd2a38f670004', null, 'com.glaway.ids.rdflow.task.entity.TaskCellDeliverItem', 'ids-rdflow-service', '', '297e02af6d18ed7d016d18f191460112', '', '1', 'cellId,userObjectId,cellName,deliverId,deliverName,deliverType,originType,inputOrOutputName,fromDeliverId,isNameStandardDefault,isOutputDeliverRequired,fileName,filePath,checked,originObjectId,originObjectName,serialVersionUID,bizId,bizVersion,policy,bizCurrent,avaliable,firstBy,firstName,firstFullName,firstOrgId,firstTime,branchIterationId,lastIterationId,latestIteration,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

--输出pm_data_source_Object
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('297e02af6d4e03d1016d4e1aa4510224', null, 'com.glaway.ids.project.plan.entity.DeliverablesInfo', 'ids-common-service', '', '297e02af6d4e03d1016d4e1aa44e0223', '', '1', 'name,useObjectType,useObjectId,useObjectCellId,useObjectName,useObjectTempId,document,fileId,origin,required,result,checked,docId,docName,formId,havePower,download,detail,serialVersionUID,bizId,bizVersion,policy,bizCurrent,avaliable,firstBy,firstName,firstFullName,firstOrgId,firstTime,branchIterationId,lastIterationId,latestIteration,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('297e02af6dce09e3016dd30bd4160009', null, 'com.glaway.ids.rdflow.task.entity.TaskCellDeliverItem', 'ids-rdflow-service', '', '297e02af6d4e03d1016d4e1aa44e0223', '', '1', 'cellId,userObjectId,cellName,deliverId,deliverName,deliverType,originType,inputOrOutputName,fromDeliverId,isNameStandardDefault,isOutputDeliverRequired,fileName,filePath,checked,originObjectId,originObjectName,serialVersionUID,bizId,bizVersion,policy,bizCurrent,avaliable,firstBy,firstName,firstFullName,firstOrgId,firstTime,branchIterationId,lastIterationId,latestIteration,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');


--资源pm_data_source_Object
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('297e02af6d3cb69c016d3e4f328d0312', null, 'com.glaway.ids.common.entity.ResourceLinkInfo', 'ids-common-service', '', '297e02af6d1e0823016d1ec0a223038d', '', '1', 'resourceId,resourceInfo,useObjectType,useObjectId,useObjectTempId,startTime,endTime,paramTime,useRate,resourceName,resourceType,serialVersionUID,bizId,bizVersion,policy,bizCurrent,avaliable,firstBy,firstName,firstFullName,firstOrgId,firstTime,branchIterationId,lastIterationId,latestIteration,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');


--问题对象信息
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('4028f0066d1de316016d1f0233bd0005', null, 'com.glaway.ids.riskproblems.problems.entity.RiskProblemInfo', 'ids-riskproblems-service', '', '4028f0066d1de316016d1f0215b60004', '', '1', '');

--风险清单对象信息
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('4028f0066d3cc740016d3f43c5ff0094', null, 'com.glaway.ids.riskproblems.config.entity.RiskTarget', 'ids-riskproblems-service', '', '4028f0066d3cc740016d3f43adbf0093', '', '1', 'code,name,avaliable,riskCategory,categoryId,categoryPath,status,remark,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

--demo质量检查单
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('4028f0066e162569016e16844b390005', null, 'com.glaway.ids.qualityTest.CofigFormTest', 'ids-pm-service', '', '4028f0066e162569016e1682ec4c0004', '', '1', 'name,checkPerson,period,approve,remark,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

--demo质量检查项
insert into pm_data_source_Object (ID, SECURITYLEVEL, OBJECTPATH, PROJECTMODEL, RESULTSQL, TABID, TABLENAME, AVALIABLE, OBJECTMODELPROPERTY)
values ('4028f0066e1a43b3016e1a4ed90a0001', null, 'com.glaway.ids.qualityTest.CofigDataGridTest', 'ids-pm-service', '', '4028f0066e1a43b3016e1a4eb6f10000', '', '1', 'name,rule,serialVersionUID,id,createBy,createName,createFullName,createTime,updateBy,updateName,updateFullName,updateTime,deleteFlag,ext1,ext2,ext3,createOrgId,updateOrgId,securityLevel,glObjParentId,parentSysTableId,parentObjectName,parentObjectBizId,containerPath,instanceEntity');

