--ЗўЮёзЂВс--
insert into FD_APPINFO (ID, DESCRIPTION, FD_APPINFOID, ROWSTAMP, APPKEY, APPNAME, CONTEXTPATH, DATABASEURL, ICON, IPADDRESS, PORT, APPTYPE, ORGID, SECURITYLEVEL, CREATEORGID, CONTAINERPATH, GLOBJPARENTID, INSTANCEENTITY, PARENTOBJECTBIZID, PARENTOBJECTNAME, PARENTSYSTABLEID)
values ('4028ef506bcf14fc016bcf435f5e0000', 'ids-pm-service', null, '2132338', 'ids-pm-service', 'ids-pm-service', '/ids-pm-service', '', '', '192.168.111.160', '18380', '1', '', null, '', '<CLOB>', '', '', '', '', '');


