-- BasicConfig
create table IDS_BASIC_CONFIG
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  FULLNAME       VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR)
);
alter table IDS_BASIC_CONFIG
  add primary key (ID);
  alter table IDS_BASIC_CONFIG
  add constraint FK_2QTCLBQTI22UR9AC7CJOBHC04 foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  -- ParamSwitch
create table CM_PARAM_SWITCH
(
  ID             VARCHAR2(255) not null,
  CREATEBY       VARCHAR2(255),
  CREATENAME     VARCHAR2(255),
  CREATETIME     DATE,
  UPDATEBY       VARCHAR2(255),
  UPDATENAME     VARCHAR2(255),
  UPDATETIME     DATE,
  AVALIABLE      VARCHAR2(255),
  BIZCURRENT     VARCHAR2(255),
  BIZID          VARCHAR2(255),
  BIZVERSION     VARCHAR2(255),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255) not null,
  NAME           VARCHAR2(255),
  STATUS         VARCHAR2(255),
  SWITCHTYPE     VARCHAR2(255),
  STATUSLIST     VARCHAR2(255),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6)
);
alter table CM_PARAM_SWITCH
  add primary key (ID);
  alter table CM_PARAM_SWITCH
  add constraint FK_U6GVE1BTS2PMQQ3JUSFGGYLV foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  -- ProjectLibRoleFileAuth
create table CM_PROJLIB_ROLE_FILE_AUTH
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  FILEID         VARCHAR2(255 CHAR),
  PERMISSIONCODE VARCHAR2(255 CHAR),
  ROLEID         VARCHAR2(255 CHAR),
  TEMPLATEID     VARCHAR2(255 CHAR)
);
alter table CM_PROJLIB_ROLE_FILE_AUTH
  add primary key (ID);
  alter table CM_PROJLIB_ROLE_FILE_AUTH
  add constraint FK_8G35FJV2KB2FWX6SH4YALQ9EK foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  -- ProjectLibTemplate
create table CM_PROJLIB_TEMPLATE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(2000 CHAR),
  STATUS         VARCHAR2(255 CHAR)
);
alter table CM_PROJLIB_TEMPLATE
  add primary key (ID);
  
  
  -- ProjectLibTemplateFileCategory
create table CM_PROJLIB_TEMPLATE_FILE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  NAME           VARCHAR2(255 CHAR),
  ORDERNUM       NUMBER(19) not null,
  PARENTID       VARCHAR2(255 CHAR),
  TEMPLATEID     VARCHAR2(255 CHAR)
);
alter table CM_PROJLIB_TEMPLATE_FILE
  add primary key (ID);

  -- ProjTemplateMenu
create table PM_TEMPLATE_MENU
(
  ID             VARCHAR2(255) not null,
  CREATEBY       VARCHAR2(255),
  CREATENAME     VARCHAR2(255),
  CREATETIME     DATE,
  UPDATEBY       VARCHAR2(255),
  UPDATENAME     VARCHAR2(255),
  UPDATETIME     DATE,
  ICONCLS        VARCHAR2(255),
  PARENTID       VARCHAR2(255),
  SORT           NUMBER(10),
  STATUS         NUMBER(10),
  TEXT           VARCHAR2(255),
  URL            VARCHAR2(255),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR)
);
alter table PM_TEMPLATE_MENU
  add primary key (ID);
  
  
  
  
  
  -- RecentlyProject
create table PM_RECENTLY_PROJECT
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PROJECTID      VARCHAR2(255 CHAR)
);
alter table PM_RECENTLY_PROJECT
  add primary key (ID);
 
  
  
  -- ApprovePlanForm
create table PM_APPROVE_PLAN_FORM
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  APPROVETYPE    VARCHAR2(255 CHAR),
  PROCINSTID     VARCHAR2(255 CHAR)
);
alter table PM_APPROVE_PLAN_FORM
  add primary key (ID);
  
  
  -- BasicLine
create table PM_BASICLINE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  BASICLINENAME  VARCHAR2(255 CHAR),
  LAUNCHTIME     DATE,
  LAUNCHER       VARCHAR2(255 CHAR),
  PROCINSTID     VARCHAR2(255 CHAR),
  PROJECTID      VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(2048 CHAR)
);
alter table PM_BASICLINE
  add primary key (ID);

  
  -- DeliverablesInfoHistory
create table PM_DELIVERABLES_INFO_HISTORY
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FILEID         VARCHAR2(255 CHAR),
  FORMID         VARCHAR2(255 CHAR),
  INFOID         VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  ORIGIN         VARCHAR2(255 CHAR),
  PLANCREATEBY   VARCHAR2(255 CHAR),
  PLANCREATETIME DATE,
  PLANUPDATEBY   VARCHAR2(255 CHAR),
  PLANUPDATENAME DATE,
  SECURITYLEVEL  NUMBER(5),
  USEOBJECTID    VARCHAR2(255 CHAR),
  USEOBJECTTYPE  VARCHAR2(255 CHAR)
);
alter table PM_DELIVERABLES_INFO_HISTORY
  add primary key (ID);
   

  
  -- InputsHistory
create table PM_INPUTS_HISTORY
(
  ID                       VARCHAR2(255 CHAR) not null,
  CREATEBY                 VARCHAR2(255 CHAR),
  CREATEFULLNAME           VARCHAR2(255 CHAR),
  CREATENAME               VARCHAR2(255 CHAR),
  CREATETIME               TIMESTAMP(6),
  DELETEFLAG               VARCHAR2(255 CHAR),
  EXT1                     VARCHAR2(255 CHAR),
  EXT2                     VARCHAR2(255 CHAR),
  EXT3                     VARCHAR2(255 CHAR),
  UPDATEBY                 VARCHAR2(255 CHAR),
  UPDATEFULLNAME           VARCHAR2(255 CHAR),
  UPDATENAME               VARCHAR2(255 CHAR),
  UPDATETIME               TIMESTAMP(6),
  FILEID                   VARCHAR2(255 CHAR),
  FORMID                   VARCHAR2(255 CHAR),
  INPUTSID                 VARCHAR2(255 CHAR),
  NAME                     VARCHAR2(255 CHAR),
  ORIGIN                   VARCHAR2(255 CHAR),
  ORIGINDELIVERABLESINFOID VARCHAR2(255 CHAR),
  ORIGINOBJECTID           VARCHAR2(255 CHAR),
  REQUIRED                 VARCHAR2(255 CHAR),
  USEOBJECTID              VARCHAR2(255 CHAR),
  USEOBJECTTYPE            VARCHAR2(255 CHAR)
);
alter table PM_INPUTS_HISTORY
  add primary key (ID);
  
  -- PlanHistory
create table PM_PLAN_HISTORY
(
  ID                 VARCHAR2(255 CHAR) not null,
  CREATEBY           VARCHAR2(255 CHAR),
  CREATEFULLNAME     VARCHAR2(255 CHAR),
  CREATENAME         VARCHAR2(255 CHAR),
  CREATETIME         TIMESTAMP(6),
  DELETEFLAG         VARCHAR2(255 CHAR),
  EXT1               VARCHAR2(255 CHAR),
  EXT2               VARCHAR2(255 CHAR),
  EXT3               VARCHAR2(255 CHAR),
  UPDATEBY           VARCHAR2(255 CHAR),
  UPDATEFULLNAME     VARCHAR2(255 CHAR),
  UPDATENAME         VARCHAR2(255 CHAR),
  UPDATETIME         TIMESTAMP(6),
  ACTUALENDTIME      DATE,
  ACTUALSTARTTIME    DATE,
  ASSIGNTIME         DATE,
  ASSIGNER           VARCHAR2(255 CHAR),
  AVALIABLE          VARCHAR2(255 CHAR),
  BIZCURRENT         VARCHAR2(255 CHAR),
  BIZID              VARCHAR2(255 CHAR),
  BIZVERSION         VARCHAR2(255 CHAR),
  CHANGETYPE         VARCHAR2(255 CHAR),
  DOCUMENTS          VARCHAR2(255 CHAR),
  FEEDBACKPROCINSTID VARCHAR2(255 CHAR),
  FEEDBACKRATEBEFORE VARCHAR2(255 CHAR),
  FLOWSTATUS         VARCHAR2(255 CHAR),
  FORMID             VARCHAR2(255 CHAR),
  INVALIDTIME        DATE,
  MILESTONE          VARCHAR2(255 CHAR),
  OPCONTENT          VARCHAR2(255 CHAR),
  OWNER              VARCHAR2(255 CHAR),
  PARENTPLANID       VARCHAR2(255 CHAR),
  PLANCREATEBY       VARCHAR2(255 CHAR),
  PLANCREATETIME     DATE,
  PLANENDTIME        DATE,
  PLANID             VARCHAR2(255 CHAR),
  PLANLEVEL          VARCHAR2(255 CHAR),
  PLANNAME           VARCHAR2(255 CHAR),
  PLANNUMBER         NUMBER(10) not null,
  PLANORDER          VARCHAR2(255 CHAR),
  PLANSOURCE         VARCHAR2(255 CHAR),
  PLANSTARTTIME      DATE,
  PLANTYPE           VARCHAR2(255 CHAR),
  PLANUPDATEBY       VARCHAR2(255 CHAR),
  PLANUPDATETIME     DATE,
  PROGRESSRATE       VARCHAR2(255 CHAR),
  PROJECTID          VARCHAR2(255 CHAR),
  PROJECTSTATUS      VARCHAR2(255 CHAR),
  REMARK             VARCHAR2(255 CHAR),
  RISK               VARCHAR2(255 CHAR),
  SECURITYLEVEL      NUMBER(5),
  STATUS             VARCHAR2(255 CHAR),
  STOREYNO           NUMBER(10),
  TASKNAMETYPE       VARCHAR2(255 CHAR),
  TASKTYPE           VARCHAR2(255 CHAR),
  WORKTIME           VARCHAR2(255 CHAR)
);
alter table PM_PLAN_HISTORY
  add primary key (ID);
CREATE INDEX INDEX_PLAN_HISTORY_PROJECTID
	ON PM_PLAN_HISTORY(PROJECTID);
CREATE INDEX INDEX_PLAN_HISTORY_ASSIGNER
	ON PM_PLAN_HISTORY(ASSIGNER);
CREATE INDEX INDEX_PLAN_HISTORY_PLANID
	ON PM_PLAN_HISTORY(PLANID);    
  
  
  -- PlanLog
create table PM_PLAN_LOG
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  FILEPATH       VARCHAR2(255 CHAR),
  LOGINFO        VARCHAR2(255 CHAR),
  PLANID         VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(1000 CHAR)
);
alter table PM_PLAN_LOG
  add primary key (ID);
  
  
  -- PreposePlan
create table PM_PREPOSE_PLAN
(
  ID             VARCHAR2(255) not null,
  CREATEBY       VARCHAR2(255),
  CREATENAME     VARCHAR2(255),
  CREATETIME     DATE,
  UPDATEBY       VARCHAR2(255),
  UPDATENAME     VARCHAR2(255),
  UPDATETIME     DATE,
  PLANID         VARCHAR2(255),
  PREPOSEPLANID  VARCHAR2(255),
  AVALIABLE      VARCHAR2(255),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR)
);
alter table PM_PREPOSE_PLAN
  add primary key (ID);
  create index INDEX_PREPOSEPLANID on PM_PREPOSE_PLAN (PREPOSEPLANID);
  create index INDEX_PREPOSE_PLANID on PM_PREPOSE_PLAN (PLANID);
  
  
  
  
  
  
  
  --ResourceLinkInfoHistory
create table PM_RESOURCE_LINK_INFO_HISTORY
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FORMID         VARCHAR2(255 CHAR),
  INFOID         VARCHAR2(255 CHAR),
  PLANCREATEBY   VARCHAR2(255 CHAR),
  PLANCREATETIME DATE,
  PLANUPDATEBY   VARCHAR2(255 CHAR),
  PLANUPDATETIME DATE,
  RESOURCEID     VARCHAR2(255 CHAR),
  RESOURCENAME   VARCHAR2(255 CHAR),
  RESOURCETYPE   VARCHAR2(255 CHAR),
  SECURITYLEVEL  NUMBER(5) not null,
  USEOBJECTID    VARCHAR2(255 CHAR),
  USEOBJECTTYPE  VARCHAR2(255 CHAR),
  USERATE        VARCHAR2(255 CHAR)
);
alter table PM_RESOURCE_LINK_INFO_HISTORY
  add primary key (ID);
  
  
  -- TempPlanDeliverablesInfo
create table PM_TEMP_PLAN_DELIVERABLES_INFO
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  DELIVERLINKID  VARCHAR2(255 CHAR),
  DELIVERABLESID VARCHAR2(255 CHAR),
  FORMID         VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  ORIGIN         VARCHAR2(255 CHAR),
  USEOBJECTID    VARCHAR2(255 CHAR),
  USEOBJECTTYPE  VARCHAR2(255 CHAR)
);
alter table PM_TEMP_PLAN_DELIVERABLES_INFO
  add primary key (ID);
  alter table PM_TEMP_PLAN_DELIVERABLES_INFO
  add constraint FK_L4444H8XTT0N47HFT2LKK9FNP foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  
  
  
  
  
  
  
  
  -- TempPlanInputs
create table PM_TEMP_PLAN_INPUTS
(
  ID                       VARCHAR2(255 CHAR) not null,
  CREATEBY                 VARCHAR2(255 CHAR),
  CREATEFULLNAME           VARCHAR2(255 CHAR),
  CREATENAME               VARCHAR2(255 CHAR),
  CREATETIME               TIMESTAMP(6),
  DELETEFLAG               VARCHAR2(255 CHAR),
  EXT1                     VARCHAR2(255 CHAR),
  EXT2                     VARCHAR2(255 CHAR),
  EXT3                     VARCHAR2(255 CHAR),
  UPDATEBY                 VARCHAR2(255 CHAR),
  UPDATEFULLNAME           VARCHAR2(255 CHAR),
  UPDATENAME               VARCHAR2(255 CHAR),
  UPDATETIME               TIMESTAMP(6),
  DOCID                    VARCHAR2(255 CHAR),
  DOCNAME                  VARCHAR2(255 CHAR),
  FILEID                   VARCHAR2(255 CHAR),
  FORMID                   VARCHAR2(255 CHAR),
  INPUTID                  VARCHAR2(255 CHAR),
  NAME                     VARCHAR2(255 CHAR),
  ORIGIN                   VARCHAR2(255 CHAR),
  ORIGINDELIVERABLESINFOID VARCHAR2(255 CHAR),
  ORIGINOBJECTID           VARCHAR2(255 CHAR),
  REQUIRED                 VARCHAR2(255 CHAR),
  USEOBJECTID              VARCHAR2(255 CHAR),
  USEOBJECTTYPE            VARCHAR2(255 CHAR)
);
alter table PM_TEMP_PLAN_INPUTS
  add primary key (ID);
  
  
  
  
  
  
  -- TempPlanResourceLinkInfo
create table PM_TEMP_PLAN_RESOURCELINK_INFO
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  ENDTIME        DATE,
  FORMID         VARCHAR2(255 CHAR),
  RESOURCEID     VARCHAR2(255 CHAR),
  RESOURCELINKID VARCHAR2(255 CHAR),
  RESOURCETYPE   VARCHAR2(255 CHAR),
  STARTTIME      DATE,
  USEOBJECTID    VARCHAR2(255 CHAR),
  USEOBJECTTYPE  VARCHAR2(255 CHAR),
  USERATE        VARCHAR2(255 CHAR)
);
alter table PM_TEMP_PLAN_RESOURCELINK_INFO
  add primary key (ID);
  alter table PM_TEMP_PLAN_RESOURCELINK_INFO
  add constraint FK_HHLLS6LN6C69BVATV6X66JS3I foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  
  
  -- PlanTemplate
create table PM_PLAN_TEMPLATE
(
  ID                VARCHAR2(255 CHAR) not null,
  CREATEBY          VARCHAR2(255 CHAR),
  CREATEFULLNAME    VARCHAR2(255 CHAR),
  CREATENAME        VARCHAR2(255 CHAR),
  CREATETIME        TIMESTAMP(6),
  DELETEFLAG        VARCHAR2(255 CHAR),
  EXT1              VARCHAR2(255 CHAR),
  EXT2              VARCHAR2(255 CHAR),
  EXT3              VARCHAR2(255 CHAR),
  UPDATEBY          VARCHAR2(255 CHAR),
  UPDATEFULLNAME    VARCHAR2(255 CHAR),
  UPDATENAME        VARCHAR2(255 CHAR),
  UPDATETIME        TIMESTAMP(6),
  AVALIABLE         VARCHAR2(255 CHAR),
  BIZCURRENT        VARCHAR2(255 CHAR),
  BIZID             VARCHAR2(255 CHAR),
  BIZVERSION        VARCHAR2(255 CHAR),
  FIRSTBY           VARCHAR2(255 CHAR),
  FIRSTFULLNAME     VARCHAR2(255 CHAR),
  FIRSTNAME         VARCHAR2(255 CHAR),
  FIRSTTIME         TIMESTAMP(6),
  SECURITYLEVEL     NUMBER(5),
  POLICY_ID         VARCHAR2(255 CHAR) not null,
  NAME              VARCHAR2(255 CHAR),
  PLANTMPLNUMBER    VARCHAR2(255 CHAR),
  PROCESSINSTANCEID VARCHAR2(255 CHAR),
  REMARK            VARCHAR2(1000 CHAR),
  STATUS            VARCHAR2(255 CHAR)
);
alter table PM_PLAN_TEMPLATE
  add primary key (ID);
  alter table PM_PLAN_TEMPLATE
  add constraint FK_957UD0S6GAB7TA7B1N1RKBT5V foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  
  
  -- PlanTemplateDetail
create table PM_PLAN_TEMPLATE_DL
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  MILESTONE      VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  NUM            NUMBER(10) not null,
  PARENTPLANID   VARCHAR2(255 CHAR),
  PLANLEVEL      VARCHAR2(255 CHAR),
  PLANNUMBER     NUMBER(10) not null,
  PLANSTARTTIME  DATE,
  PLANTEMPLATEID VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(1000 CHAR),
  WORKTIME       VARCHAR2(255 CHAR),
  STOREYNO       NUMBER(10),
  ISNECESSARY    VARCHAR2(255 CHAR),
  PROJECTTEMPLATEID VARCHAR2(255 CHAR),
  TABCBTEMPLATEID   VARCHAR2(255 CHAR),
  TASKNAMETYPE      VARCHAR2(255 CHAR)
);
alter table PM_PLAN_TEMPLATE_DL
  add primary key (ID);
  alter table PM_PLAN_TEMPLATE_DL
  add constraint FK_3CXPOV4WUC13DOVBA4TM3589T foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  
  -- PreposePlanTemplate
create table PM_PREPOSE_PLAN_TEMPLATE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  PLANID         VARCHAR2(255 CHAR),
  PREPOSEPLANID  VARCHAR2(255 CHAR)
);
alter table PM_PREPOSE_PLAN_TEMPLATE
  add primary key (ID);
  
  
  
  
  
  
  --ProjDocRelation
create table PM_PROJ_DOC_RELATION
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  DOCID          VARCHAR2(255 CHAR),
  QUOTEID        VARCHAR2(255 CHAR)
);
alter table PM_PROJ_DOC_RELATION
  add primary key (ID);
  alter table PM_PROJ_DOC_RELATION
  add constraint FK_H7NYLT12KFS2EEIPMMJA37ID7 foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  -- ProjectFileCodeRule
create table PM_PROJECT_FILE_CODE_RULE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  CURVAL         VARCHAR2(255 CHAR),
  NEXTVAL        VARCHAR2(255 CHAR),
  PROJECTNO      VARCHAR2(255 CHAR)
);
alter table PM_PROJECT_FILE_CODE_RULE
  add primary key (ID);
  alter table PM_PROJECT_FILE_CODE_RULE
  add constraint FK_1MUI4MFYRF6YURCEBK0ABQSJP foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  -- ProjectLibAuthTemplateLink
create table PM_PROJECTLIB_TEMPLATE_LINK
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PROJECTID      VARCHAR2(255 CHAR),
  TEMPLATEID     VARCHAR2(255 CHAR)
);
alter table PM_PROJECTLIB_TEMPLATE_LINK
  add primary key (ID);
  
  
  
  
  
  -- ProjLibFile
create table PM_PROJ_LIB_FILE
(
  ID                 VARCHAR2(255 CHAR) not null,
  CREATEBY           VARCHAR2(255 CHAR),
  CREATEFULLNAME     VARCHAR2(255 CHAR),
  CREATENAME         VARCHAR2(255 CHAR),
  CREATETIME         TIMESTAMP(6),
  DELETEFLAG         VARCHAR2(255 CHAR),
  EXT1               VARCHAR2(255 CHAR),
  EXT2               VARCHAR2(255 CHAR),
  EXT3               VARCHAR2(255 CHAR),
  UPDATEBY           VARCHAR2(255 CHAR),
  UPDATEFULLNAME     VARCHAR2(255 CHAR),
  UPDATENAME         VARCHAR2(255 CHAR),
  UPDATETIME         TIMESTAMP(6),
  AVALIABLE          VARCHAR2(255 CHAR),
  BIZCURRENT         VARCHAR2(255 CHAR),
  BIZID              VARCHAR2(255 CHAR),
  BIZVERSION         VARCHAR2(255 CHAR),
  FIRSTBY            VARCHAR2(255 CHAR),
  FIRSTFULLNAME      VARCHAR2(255 CHAR),
  FIRSTNAME          VARCHAR2(255 CHAR),
  FIRSTTIME          TIMESTAMP(6),
  SECURITYLEVEL      NUMBER(5),
  POLICY_ID          VARCHAR2(255 CHAR) not null,
  FEEDBACKPROCINSTID VARCHAR2(255 CHAR),
  OLDTASKID          VARCHAR2(255 CHAR),
  PROJECTFILEID      VARCHAR2(255 CHAR),
  PROJECTSTATUS      VARCHAR2(255 CHAR)
);
alter table PM_PROJ_LIB_FILE
  add primary key (ID);
  alter table PM_PROJ_LIB_FILE
  add constraint FK_MXH67APOXVMU4LVT0L42NI2PA foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  -- ProjLog
create table PM_PROJ_LOG
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  CREATEUSERNAME VARCHAR2(255 CHAR),
  LOGINFO        VARCHAR2(255 CHAR),
  PROJECTNUMBER  VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(500 CHAR)
);
alter table PM_PROJ_LOG
  add primary key (ID);
  alter table PM_PROJ_LOG
  add constraint FK_EWMTKT1QYE92DRI6TNR191QNK foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  -- ProjWarn
create table PM_PROJECT_WARN
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  FLAG           VARCHAR2(255 CHAR),
  PROJECTNUM     VARCHAR2(4000 CHAR),
  USERNAME       VARCHAR2(255 CHAR)
);
alter table PM_PROJECT_WARN
  add primary key (ID);
  
  
  
  
  -- PreposeProjTemplate
create table PM_PREPOSE_PROJ_TEMPLATE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PLANID         VARCHAR2(255 CHAR),
  PREPOSEPLANID  VARCHAR2(255 CHAR)
);
alter table PM_PREPOSE_PROJ_TEMPLATE
  add primary key (ID);
  
  
  
  -- ProjTemplate
create table PM_PROJ_TEMPLATE
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  PROJTMPLNAME   VARCHAR2(255 CHAR),
  PROJTMPLNUMBER VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(1024 CHAR),
  STATUS         VARCHAR2(255 CHAR)
);
alter table PM_PROJ_TEMPLATE
  add primary key (ID);
  alter table PM_PROJ_TEMPLATE
  add constraint FK_1RYKEQ1XCRR6WX7H4CQ0SREME foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  -- ProjTemplateDetail
create table PM_PROJ_TEMPLATE_DETAIL
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  DOCUMENTS      VARCHAR2(255 CHAR),
  MILESTONE      VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  NUM            NUMBER(10) not null,
  PARENTPLANID   VARCHAR2(255 CHAR),
  PHASE          VARCHAR2(255 CHAR),
  PLANLEVEL      VARCHAR2(255 CHAR),
  PLANNUMBER     NUMBER(10) not null,
  PROJTEMPLATEID VARCHAR2(255 CHAR),
  REMARK         VARCHAR2(255 CHAR),
  WORKTIME       VARCHAR2(255 CHAR)
);
alter table PM_PROJ_TEMPLATE_DETAIL
  add primary key (ID);
  alter table PM_PROJ_TEMPLATE_DETAIL
  add constraint FK_S4WNY6UWTBPEL2VPU4MX8CLUX foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
  
  
  
  
  
  -- projecttemplate_ProjTmplTeamLink
create table PM_PROJ_TMPL_TEAM_LINK
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  AVALIABLE      VARCHAR2(255 CHAR),
  BIZCURRENT     VARCHAR2(255 CHAR),
  BIZID          VARCHAR2(255 CHAR),
  BIZVERSION     VARCHAR2(255 CHAR),
  FIRSTBY        VARCHAR2(255 CHAR),
  FIRSTFULLNAME  VARCHAR2(255 CHAR),
  FIRSTNAME      VARCHAR2(255 CHAR),
  FIRSTTIME      TIMESTAMP(6),
  SECURITYLEVEL  NUMBER(5),
  POLICY_ID      VARCHAR2(255 CHAR) not null,
  LIBID          VARCHAR2(255 CHAR),
  PROJTEMPLATEID VARCHAR2(255 CHAR),
  TEAMID         VARCHAR2(255 CHAR)
);
alter table PM_PROJ_TMPL_TEAM_LINK
  add primary key (ID);
  alter table PM_PROJ_TMPL_TEAM_LINK
  add constraint FK_LAG7191PFKS7TB2P69RPPH67D foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
   
  -- PLANVIEW_INFO--
create table PLANVIEW_INFO
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  ISDEFAULT      VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  PUBLISHDEPT    VARCHAR2(255 CHAR),
  PUBLISHPERSON  VARCHAR2(255 CHAR),
  PUBLISHTIME    TIMESTAMP(6),
  STATUS         VARCHAR2(255 CHAR)
);
alter table PLANVIEW_INFO
  add primary key (ID);
  
--PLANVIEW_SET_CONDITION--
create table PLANVIEW_SET_CONDITION
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  DEPARTMENTID   VARCHAR2(255 CHAR),
  PLANVIEWINFOID VARCHAR2(255 CHAR),
  SHOWRANGE      VARCHAR2(255 CHAR),
  TIMERANGE      VARCHAR2(255 CHAR),
  PLANID      VARCHAR2(255 CHAR)
);
alter table PLANVIEW_SET_CONDITION
  add primary key (ID);
  
--PLANVIEW_SEARCH_CONDITION--
create table PLANVIEW_SEARCH_CONDITION
(
  ID                 VARCHAR2(255 CHAR) not null,
  CREATEBY           VARCHAR2(255 CHAR),
  CREATEFULLNAME     VARCHAR2(255 CHAR),
  CREATENAME         VARCHAR2(255 CHAR),
  CREATETIME         TIMESTAMP(6),
  DELETEFLAG         VARCHAR2(255 CHAR),
  EXT1               VARCHAR2(255 CHAR),
  EXT2               VARCHAR2(255 CHAR),
  EXT3               VARCHAR2(255 CHAR),
  UPDATEBY           VARCHAR2(255 CHAR),
  UPDATEFULLNAME     VARCHAR2(255 CHAR),
  UPDATENAME         VARCHAR2(255 CHAR),
  UPDATETIME         TIMESTAMP(6),
  ATTRIBUTECONDITION VARCHAR2(255 CHAR),
  ATTRIBUTENAME      VARCHAR2(255 CHAR),
  ATTRIBUTEVALUE     VARCHAR2(255 CHAR),
  PLANVIEWINFOID     VARCHAR2(255 CHAR)
);
alter table PLANVIEW_SEARCH_CONDITION
  add primary key (ID);
  
--PLANVIEW_APPLY_PROJECT--
create table PLANVIEW_APPLY_PROJECT
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PLANVIEWINFOID VARCHAR2(255 CHAR),
  PROJECTID      VARCHAR2(255 CHAR)
);
alter table PLANVIEW_APPLY_PROJECT
  add primary key (ID);
  
--PLANVIEW_APPLY_USER--
create table PLANVIEW_APPLY_USER
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PLANVIEWINFOID VARCHAR2(255 CHAR),
  USERID         VARCHAR2(255 CHAR)
);
alter table PLANVIEW_APPLY_USER
  add primary key (ID);

-- PLANVIEW_USER_PROJECT--
create table PLANVIEW_USER_PROJECT
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PLANVIEWINFOID VARCHAR2(255 CHAR),
  PROJECTID      VARCHAR2(255 CHAR),
  USERID         VARCHAR2(255 CHAR)
);
alter table PLANVIEW_USER_PROJECT
  add primary key (ID);
  
-- Create table PLANVIEW_COLUMN_INFO
create table PLANVIEW_COLUMN_INFO
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  COLUMNID       VARCHAR2(255 CHAR),
  PLANVIEWINFOID VARCHAR2(255 CHAR)
);
alter table PLANVIEW_COLUMN_INFO
  add primary key (ID);
  
-- ProjTmpLibAuthLibTmpLink
create table PM_PROJ_TMPL_LIBTMP_LINK
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  PROJTMPID      VARCHAR2(255 CHAR),
  LIBTMPID     VARCHAR2(255 CHAR)
);
alter table PM_PROJ_TMPL_LIBTMP_LINK
  add primary key (ID);
  
-- PlanTempOptLog
create table PLAN_TEMPLATE_OPT_LOG
(
  ID             VARCHAR2(255 CHAR) not null,
  CREATEBY       VARCHAR2(255 CHAR),
  CREATEFULLNAME VARCHAR2(255 CHAR),
  CREATENAME     VARCHAR2(255 CHAR),
  CREATETIME     TIMESTAMP(6),
  DELETEFLAG     VARCHAR2(255 CHAR),
  EXT1           VARCHAR2(255 CHAR),
  EXT2           VARCHAR2(255 CHAR),
  EXT3           VARCHAR2(255 CHAR),
  UPDATEBY       VARCHAR2(255 CHAR),
  UPDATEFULLNAME VARCHAR2(255 CHAR),
  UPDATENAME     VARCHAR2(255 CHAR),
  UPDATETIME     TIMESTAMP(6),
  LOGINFO        VARCHAR2(255 CHAR),
  TMPLID         VARCHAR2(255 CHAR)
);
alter table PLAN_TEMPLATE_OPT_LOG
  add primary key (ID);

create table PM_OBJECT_PROPERTY_INFO
(
  ID                VARCHAR2(255 CHAR) not null,
  CONTAINERPATH     CLOB,
  CREATEBY          VARCHAR2(255 CHAR),
  CREATEFULLNAME    VARCHAR2(255 CHAR),
  CREATENAME        VARCHAR2(255 CHAR),
  CREATEORGID       VARCHAR2(255 CHAR),
  CREATETIME        TIMESTAMP(6),
  DELETEFLAG        VARCHAR2(255 CHAR),
  EXT1              VARCHAR2(255 CHAR),
  EXT2              VARCHAR2(255 CHAR),
  EXT3              VARCHAR2(255 CHAR),
  GLOBJPARENTID     VARCHAR2(255 CHAR),
  INSTANCEENTITY    VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID VARCHAR2(255 CHAR),
  PARENTOBJECTNAME  VARCHAR2(255 CHAR),
  PARENTSYSTABLEID  VARCHAR2(255 CHAR),
  SECURITYLEVEL     NUMBER(5),
  UPDATEBY          VARCHAR2(255 CHAR),
  UPDATEFULLNAME    VARCHAR2(255 CHAR),
  UPDATENAME        VARCHAR2(255 CHAR),
  UPDATEORGID       VARCHAR2(255 CHAR),
  UPDATETIME        TIMESTAMP(6),
  CONTROL           VARCHAR2(255 CHAR),
  DATASOURCEID      VARCHAR2(255 CHAR),
  DISPLAY           VARCHAR2(255 CHAR),
  FORMAT            VARCHAR2(255 CHAR),
  OBJECTPATH        VARCHAR2(255 CHAR),
  OPERATIONEVENT    VARCHAR2(255 CHAR),
  ORDERNUMBER       VARCHAR2(255 CHAR),
  PROPERTYNAME      VARCHAR2(255 CHAR),
  PROPERTYVALUE     VARCHAR2(255 CHAR),
  READWRITEACCESS   VARCHAR2(255 CHAR),
  REQUIRED          NUMBER(1) not null,
  AVALIABLE         VARCHAR2(255 CHAR)
);
alter table PM_OBJECT_PROPERTY_INFO
  add primary key (ID);
  
create table PM_COMBINATION_TEMPLATE_INFO
(
  ID                       VARCHAR2(255 CHAR) not null,
  CONTAINERPATH            CLOB,
  CREATEBY                 VARCHAR2(255 CHAR),
  CREATEFULLNAME           VARCHAR2(255 CHAR),
  CREATENAME               VARCHAR2(255 CHAR),
  CREATEORGID              VARCHAR2(255 CHAR),
  CREATETIME               TIMESTAMP(6),
  DELETEFLAG               VARCHAR2(255 CHAR),
  EXT1                     VARCHAR2(255 CHAR),
  EXT2                     VARCHAR2(255 CHAR),
  EXT3                     VARCHAR2(255 CHAR),
  GLOBJPARENTID            VARCHAR2(255 CHAR),
  INSTANCEENTITY           VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID        VARCHAR2(255 CHAR),
  PARENTOBJECTNAME         VARCHAR2(255 CHAR),
  PARENTSYSTABLEID         VARCHAR2(255 CHAR),
  SECURITYLEVEL            NUMBER(5),
  UPDATEBY                 VARCHAR2(255 CHAR),
  UPDATEFULLNAME           VARCHAR2(255 CHAR),
  UPDATENAME               VARCHAR2(255 CHAR),
  UPDATEORGID              VARCHAR2(255 CHAR),
  UPDATETIME               TIMESTAMP(6),
  DISPLAYACCESS            VARCHAR2(255 CHAR),
  NAME                     VARCHAR2(255 CHAR),
  ORDERNUM                 NUMBER(10) not null,
  TABCOMBINATIONTEMPLATEID VARCHAR2(255 CHAR),
  TYPEID                   VARCHAR2(255 CHAR)
);
alter table PM_COMBINATION_TEMPLATE_INFO
  add primary key (ID);
  
create table PM_DATA_SOURCE_OBJECT
(
  ID                  VARCHAR2(255 CHAR) not null,
  CONTAINERPATH       CLOB,
  CREATEBY            VARCHAR2(255 CHAR),
  CREATEFULLNAME      VARCHAR2(255 CHAR),
  CREATENAME          VARCHAR2(255 CHAR),
  CREATEORGID         VARCHAR2(255 CHAR),
  CREATETIME          TIMESTAMP(6),
  DELETEFLAG          VARCHAR2(255 CHAR),
  EXT1                VARCHAR2(255 CHAR),
  EXT2                VARCHAR2(255 CHAR),
  EXT3                VARCHAR2(255 CHAR),
  GLOBJPARENTID       VARCHAR2(255 CHAR),
  INSTANCEENTITY      VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID   VARCHAR2(255 CHAR),
  PARENTOBJECTNAME    VARCHAR2(255 CHAR),
  PARENTSYSTABLEID    VARCHAR2(255 CHAR),
  SECURITYLEVEL       NUMBER(5),
  UPDATEBY            VARCHAR2(255 CHAR),
  UPDATEFULLNAME      VARCHAR2(255 CHAR),
  UPDATENAME          VARCHAR2(255 CHAR),
  UPDATEORGID         VARCHAR2(255 CHAR),
  UPDATETIME          TIMESTAMP(6),
  DATATOINTERFACE     VARCHAR2(255 CHAR),
  OBJECTPATH          VARCHAR2(255 CHAR),
  PROJECTMODEL        VARCHAR2(255 CHAR),
  RESULTSQL           VARCHAR2(255 CHAR),
  TABID               VARCHAR2(255 CHAR),
  TABLENAME           VARCHAR2(255 CHAR),
  AVALIABLE           VARCHAR2(255 CHAR),
  OBJECTMODELPROPERTY CLOB
);
alter table PM_DATA_SOURCE_OBJECT
  add primary key (ID);
  
  create table PM_ACTIVITY_TYPE_MANAGE
(
  ID                VARCHAR2(255 CHAR) not null,
  CONTAINERPATH     CLOB,
  CREATEBY          VARCHAR2(255 CHAR),
  CREATEFULLNAME    VARCHAR2(255 CHAR),
  CREATENAME        VARCHAR2(255 CHAR),
  CREATEORGID       VARCHAR2(255 CHAR),
  CREATETIME        TIMESTAMP(6),
  DELETEFLAG        VARCHAR2(255 CHAR),
  EXT1              VARCHAR2(255 CHAR),
  EXT2              VARCHAR2(255 CHAR),
  EXT3              VARCHAR2(255 CHAR),
  GLOBJPARENTID     VARCHAR2(255 CHAR),
  INSTANCEENTITY    VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID VARCHAR2(255 CHAR),
  PARENTOBJECTNAME  VARCHAR2(255 CHAR),
  PARENTSYSTABLEID  VARCHAR2(255 CHAR),
  SECURITYLEVEL     NUMBER(5),
  UPDATEBY          VARCHAR2(255 CHAR),
  UPDATEFULLNAME    VARCHAR2(255 CHAR),
  UPDATENAME        VARCHAR2(255 CHAR),
  UPDATEORGID       VARCHAR2(255 CHAR),
  UPDATETIME        TIMESTAMP(6),
  AVALIABLE         VARCHAR2(255 CHAR),
  CODE              VARCHAR2(255 CHAR),
  NAME              VARCHAR2(255 CHAR),
  REMAKE            VARCHAR2(255 CHAR),
  STATUS            VARCHAR2(255 CHAR),
  REMARK            VARCHAR2(255 CHAR),
  SOURCE            VARCHAR2(255 CHAR)
);
alter table PM_ACTIVITY_TYPE_MANAGE
  add primary key (ID);
  
create table PM_TAB_COMBINATION_TEMPLATE
(
  ID                VARCHAR2(255 CHAR) not null,
  CONTAINERPATH     CLOB,
  CREATEBY          VARCHAR2(255 CHAR),
  CREATEFULLNAME    VARCHAR2(255 CHAR),
  CREATENAME        VARCHAR2(255 CHAR),
  CREATEORGID       VARCHAR2(255 CHAR),
  CREATETIME        TIMESTAMP(6),
  DELETEFLAG        VARCHAR2(255 CHAR),
  EXT1              VARCHAR2(255 CHAR),
  EXT2              VARCHAR2(255 CHAR),
  EXT3              VARCHAR2(255 CHAR),
  GLOBJPARENTID     VARCHAR2(255 CHAR),
  INSTANCEENTITY    VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID VARCHAR2(255 CHAR),
  PARENTOBJECTNAME  VARCHAR2(255 CHAR),
  PARENTSYSTABLEID  VARCHAR2(255 CHAR),
  SECURITYLEVEL     NUMBER(5),
  UPDATEBY          VARCHAR2(255 CHAR),
  UPDATEFULLNAME    VARCHAR2(255 CHAR),
  UPDATENAME        VARCHAR2(255 CHAR),
  UPDATEORGID       VARCHAR2(255 CHAR),
  UPDATETIME        TIMESTAMP(6),
  ACTIVITYID        VARCHAR2(255 CHAR),
  CODE              VARCHAR2(255 CHAR),
  NAME              VARCHAR2(255 CHAR),
  REMAKE            VARCHAR2(255 CHAR),
  STATUS            VARCHAR2(255 CHAR),
  TEMPLATENAME      VARCHAR2(255 CHAR),
  AVALIABLE         VARCHAR2(255 CHAR),
  BIZCURRENT        VARCHAR2(255 CHAR),
  BIZID             VARCHAR2(255 CHAR),
  BIZVERSION        VARCHAR2(255 CHAR),
  BRANCHITERATIONID VARCHAR2(255 CHAR),
  FIRSTBY           VARCHAR2(255 CHAR),
  FIRSTFULLNAME     VARCHAR2(255 CHAR),
  FIRSTNAME         VARCHAR2(255 CHAR),
  FIRSTORGID        VARCHAR2(255 CHAR),
  FIRSTTIME         TIMESTAMP(6),
  LASTITERATIONID   VARCHAR2(255 CHAR),
  LATESTITERATION   VARCHAR2(255 CHAR),
  POLICY_ID         VARCHAR2(255 CHAR) not null,
  PROCESSINSTANCEID VARCHAR2(255 CHAR)
);
alter table PM_TAB_COMBINATION_TEMPLATE
  add primary key (ID);
  alter table PM_TAB_COMBINATION_TEMPLATE
  add constraint FK_QWJC5KVQD9YAYHPNK34J4PCR6 foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);
  
create table PM_TAB_TEMPLATE
(
  ID                VARCHAR2(255 CHAR) not null,
  CONTAINERPATH     CLOB,
  CREATEBY          VARCHAR2(255 CHAR),
  CREATEFULLNAME    VARCHAR2(255 CHAR),
  CREATENAME        VARCHAR2(255 CHAR),
  CREATEORGID       VARCHAR2(255 CHAR),
  CREATETIME        TIMESTAMP(6),
  DELETEFLAG        VARCHAR2(255 CHAR),
  EXT1              VARCHAR2(255 CHAR),
  EXT2              VARCHAR2(255 CHAR),
  EXT3              VARCHAR2(255 CHAR),
  GLOBJPARENTID     VARCHAR2(255 CHAR),
  INSTANCEENTITY    VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID VARCHAR2(255 CHAR),
  PARENTOBJECTNAME  VARCHAR2(255 CHAR),
  PARENTSYSTABLEID  VARCHAR2(255 CHAR),
  SECURITYLEVEL     NUMBER(5),
  UPDATEBY          VARCHAR2(255 CHAR),
  UPDATEFULLNAME    VARCHAR2(255 CHAR),
  UPDATENAME        VARCHAR2(255 CHAR),
  UPDATEORGID       VARCHAR2(255 CHAR),
  UPDATETIME        TIMESTAMP(6),
  CODE              VARCHAR2(255 CHAR),
  DISPLAYUSAGE      VARCHAR2(255 CHAR),
  EXTERNALURL       VARCHAR2(255 CHAR),
  NAME              VARCHAR2(255 CHAR),
  REMAKE            VARCHAR2(255 CHAR),
  SOURCE            VARCHAR2(255 CHAR),
  STOPFLAG          VARCHAR2(255 CHAR),
  TABTYPE           VARCHAR2(255 CHAR),
  AVALIABLE         VARCHAR2(255 CHAR),
  BIZCURRENT        VARCHAR2(255 CHAR),
  BIZID             VARCHAR2(255 CHAR),
  BIZVERSION        VARCHAR2(255 CHAR),
  BRANCHITERATIONID VARCHAR2(255 CHAR),
  FIRSTBY           VARCHAR2(255 CHAR),
  FIRSTFULLNAME     VARCHAR2(255 CHAR),
  FIRSTNAME         VARCHAR2(255 CHAR),
  FIRSTORGID        VARCHAR2(255 CHAR),
  FIRSTTIME         TIMESTAMP(6),
  LASTITERATIONID   VARCHAR2(255 CHAR),
  LATESTITERATION   VARCHAR2(255 CHAR),
  POLICY_ID         VARCHAR2(255 CHAR) not null,
  PROCESSINSTANCEID VARCHAR2(255 CHAR)
);
alter table PM_TAB_TEMPLATE
  add primary key (ID);
  alter table PM_TAB_TEMPLATE
  add constraint FK_JRHT5N2GM6PJ2HGRRJV0BCG1P foreign key (POLICY_ID)
  references LIFE_CYCLE_POLICY (ID);

create table PM_PLAN_FEEDBACK
(
  ID                VARCHAR2(255 CHAR) not null,
  CONTAINERPATH     CLOB,
  CREATEBY          VARCHAR2(255 CHAR),
  CREATEFULLNAME    VARCHAR2(255 CHAR),
  CREATENAME        VARCHAR2(255 CHAR),
  CREATEORGID       VARCHAR2(255 CHAR),
  CREATETIME        TIMESTAMP(6),
  DELETEFLAG        VARCHAR2(255 CHAR),
  EXT1              VARCHAR2(255 CHAR),
  EXT2              VARCHAR2(255 CHAR),
  EXT3              VARCHAR2(255 CHAR),
  GLOBJPARENTID     VARCHAR2(255 CHAR),
  INSTANCEENTITY    VARCHAR2(255 CHAR),
  PARENTOBJECTBIZID VARCHAR2(255 CHAR),
  PARENTOBJECTNAME  VARCHAR2(255 CHAR),
  PARENTSYSTABLEID  VARCHAR2(255 CHAR),
  SECURITYLEVEL     NUMBER(5),
  UPDATEBY          VARCHAR2(255 CHAR),
  UPDATEFULLNAME    VARCHAR2(255 CHAR),
  UPDATENAME        VARCHAR2(255 CHAR),
  UPDATEORGID       VARCHAR2(255 CHAR),
  UPDATETIME        TIMESTAMP(6),
  LIFECYCLESTATUS   VARCHAR2(255 CHAR),
  WEIGHTPERCENT     VARCHAR2(255 CHAR)
);
alter table PM_PLAN_FEEDBACK
  add primary key (ID);